dist: trusty
language: node_js
node_js:
   - "7"
sudo: false

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

branches:
  only:
    - master
    - dev

install:
  - npm install

script:
  - npm test
  #- if [[ $TRAVIS_BRANCH != 'master' ]]; then branch='dev'; fi;
  - export DATABASE=cognicity; npm run build
  - git clone -b server-object-refactor https://github.com/urbanriskmap/cognicity-server.git urbanriskmap/cognicity-server ; cd urbanriskmap/cognicity-server ; npm install ; npm test
