language: node_js
node_js:
   - "7"
sudo: false

addons:
  postgresql: "9.5"
services: postgresql

branches:
  only:
    - master
    - dev

before_install: bash ./build/run.sh

install:
  - npm install
