dist: trusty
language: node_js
node_js:
   - "6.10.0"
sudo: false

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.4

branches:
  only:
    - master
    - dev

install:
  - npm install

before_script:
  - psql -U travis -p 5432 -c "SELECT '5432', PostGIS_full_version()"
  - psql -U travis -p 5433 -c "SELECT '5433', PostGIS_full_version()"


script:
  - npm test

after_success:
  - if [[ $TRAVIS_BRANCH != 'master' ]]; then BRANCH='dev'; else BRANCH='master'; fi;
  - export PGDATABASE=cognicity; npm run build
  - git clone -b $BRANCH https://github.com/urbanriskmap/cognicity-server.git urbanriskmap/cognicity-server ; cd urbanriskmap/cognicity-server ; npm install ; npm test
