dist: trusty
language: node_js
node_js:
   - "6.10.0"
sudo: false

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

branches:
  only:
    - master
    - dev

install:
  - npm install

script:
  - npm test

after_success:
  - if [[ $TRAVIS_BRANCH != 'master' ]]; then BRANCH='dev'; else BRANCH='master'; fi;
  - export PGDATABASE=cognicity; npm run build
  - git clone -b $BRANCH https://github.com/urbanriskmap/cognicity-server.git urbanriskmap/cognicity-server ; cd urbanriskmap/cognicity-server ; npm install ; npm test
